### ISSUE TITLE
Document artBot

### ISSUE THREAD

**Issue by AFTERWAKE** [AFTERWAKE/IRCBots#5]
Add a `README.md `to [artBot/](https://github.com/AFTERWAKE/IRCBots/tree/master/artBot) and add artBot info to the repository `README.md`

See [theCount](https://github.com/AFTERWAKE/IRCBots/tree/master/theCount) or [Doge](https://github.com/AFTERWAKE/IRCBots/tree/master/doge) for good examples.

**Comment by ldavis125** [comment]
This issue is mitigated in my latest pull request.
